controller_names:
  - scaled_joint_trajectory_controller
  - joint_trajectory_controller
  - delto_controller


scaled_joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: true
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint


joint_trajectory_controller:
  action_ns: follow_joint_trajectory
  type: FollowJointTrajectory
  default: false
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint

  delto_controller:
    joints:
      - F1M1
      - F1M2
      - F1M3
      - F1M4
      - F2M1
      - F2M2
      - F2M3
      - F2M4
      - F3M1
      - F3M2
      - F3M3
      - F3M4
    command_interfaces:
      - position
